[project]
name = "code-agent-switch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chenyifan", email = "3149107774@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
code-agent-switch = "code_agent_switch:main"
cas = "code_agent_switch:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
