[project]
name = "agent-switch"
version = "0.1.0"
description = "Provider switcher for Claude Code, Codex & OpenCode"
readme = "README.md"
authors = [
    { name = "chenyifan", email = "3149107774@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
agent-switch = "agent_switch:main"
asw = "agent_switch:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
